name: task_8
description: Local DB, WebServices, BLOC & Widget=
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  home_widget: ^0.3.0
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  dio: ^5.3.2
  retrofit: ^4.0.1
  shared_preferences: ^2.2.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  cached_network_image: ^3.2.3



dev_dependencies:
  freezed: ^2.4.2
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
